### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [airo-github/RFA_record#93]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
こちら確認できました。LGTMです。

## 静的コードチェックが入っている
現状問題無さそうです。ただ人の目だけでは漏れがありうるのでRubocopを入れてチェックをしましょう。

## 就活において十分な技術力を示せる機能を実装しているか
概ね一定基準を満たしていると思われます。そのまま開発をしながら就活も進めましょう。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・Web側のヘッダーが最下部になかったりと、各所でページ表示で気になる箇所が散見されたので調整してください。
・LINE上の表記も文字列が並んでいるだけになっているので、枠線から少し話してみたり調整を行いましょう。
・ページネーションもより直感的に使いやすいように手を加えましょう。（おそらくデフォルトのままかと思われます）
・写真投稿のページも画像を送付するボタンの配置、ヘッダーの配置、注意書きのインパクトが大きすぎるetc、ユーザーにとって違和感を感じさせないように調整してください。
・活動内容を更新する入力欄も枠がズレていたり、他の項目に誤ってタップしないか、全体的にちょっと左側から話すなど調整しましょう。
・README.mdも更新しましょう。現状だとゲームを所持していないorやったことがない人には挙動確認のしようがないため、README.mdにデモを掲載したり、登録用の画像を用意したり、Webアプリケーション確認者にストレスが無いように整えましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by airo-github** [comment]
レビューありがとうございます。
以下におおまかなスケジュールを記載します。

- リマインド機能（2日）
- グラフの週間、月間表示機能（2日）
- 各レイアウト修正（3日）
- リファクタリング（2日）
この週末は予定があるため来週月曜からのスタートとし10/24(火)本リリース予定です。

**Comment by Tsuchiya2** [comment]
ご回答ありがとうございます。
引き続き開発頑張ってください。
